### ISSUE TITLE
I do not think the search works after E22.

### ISSUE THREAD

**Issue by Nothing-Works** [zaiste/flutter-in-practice#1]
I do not think the search works after E22. The search on the contact page.

**Comment by zaiste** [comment]
@Nothing-Works Yes, that's true. I broke some things in the process. I'll address that in the upcoming episode.

**Comment by zaiste** [comment]
@Nothing-Works this is now resolved as of E26

**Comment by Nothing-Works** [comment]
@zaiste  Thank you very much!
